/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoice.ui;

import application.Application;
import entity.invoice.Invoice;
import entity.invoice.InvoiceManager;
import java.awt.event.KeyEvent;
import ui.controls.PressButton;

/**
 *
 * @author PersianDevStudio
 */
public class InvoiceIdInputDialog extends javax.swing.JDialog {

    private Invoice selectedInvoice;

    /**
     * Creates new form InvoiceIdInputDialog
     *
     * @param parent
     * @param modal
     */
    public InvoiceIdInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        pressButton1.setTextHorizontalPosition(PressButton.POSITION_CENTER);
        pressButton1.setTextVerticalPosition(PressButton.POSITION_CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textView1 = new ui.controls.TextView();
        inputFieldNumber1 = new ui.controls.input.InputFieldNumber();
        pressButton1 = new ui.controls.PressButton();
        textView2 = new ui.controls.TextView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textView1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textView1.setText("شماره فاکتور مورد نظر را وارد کنید");

        inputFieldNumber1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputFieldNumber1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputFieldNumber1KeyPressed(evt);
            }
        });

        pressButton1.setText("تایید");
        pressButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButton1ActionPerformed(evt);
            }
        });

        textView2.setForeground(new java.awt.Color(255, 0, 0));
        textView2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textView2.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputFieldNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pressButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(textView2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFieldNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pressButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pressButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButton1ActionPerformed
        search();
    }//GEN-LAST:event_pressButton1ActionPerformed

    private void inputFieldNumber1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFieldNumber1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            search();
        }
    }//GEN-LAST:event_inputFieldNumber1KeyPressed

    private void search() {
        try {
            Invoice find = InvoiceManager.find(Long.parseLong(inputFieldNumber1.getText()));
            if (find == null) {
                textView2.setText("فاکتوری پیدا نشد!");
                return;
            } else {
                selectedInvoice = find;
            }
            dispose();
        } catch (Exception e) {
            textView2.setText("ورودی نا معتبر است.");
        }
    }

    public static Invoice open() {
        /* Create and display the dialog */
        InvoiceIdInputDialog dialog = new InvoiceIdInputDialog(Application.instance, true);
        dialog.setTitle("جستجوی فاکتور");
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

        return dialog.selectedInvoice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.controls.input.InputFieldNumber inputFieldNumber1;
    private ui.controls.PressButton pressButton1;
    private ui.controls.TextView textView1;
    private ui.controls.TextView textView2;
    // End of variables declaration//GEN-END:variables
}
