/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report.ui;

import application.Application;

/**
 *
 * @author PersianDevStudio
 */
public class ItemPricingDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public ItemPricingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pricingPanel1 = new pricing.ui.PricingPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(pricingPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void open() {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ItemPricingDialog dialog = new ItemPricingDialog(Application.instance, true);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pricing.ui.PricingPanel pricingPanel1;
    // End of variables declaration//GEN-END:variables
}
