/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report.ui;

import invoice.ui.CustomFocusTraversalPolicy;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import report.ReportCustomerItemBill;
import ui.container.GroupPane;
import ui.container.TabbedContainer;
import ui.controls.PressButton;

/**
 *
 * @author PersianDevStudio
 */
public class ReportPanelCustomerItemBill extends GroupPane {

    private ReportCustomerItemBill reportCustomerItemBill;
    private TabbedContainer tabbedPane;

    /**
     * Creates new form NewJPanel
     */
    public ReportPanelCustomerItemBill() {
        initComponents();

        pressButtonReport.setTextHorizontalPosition(PressButton.POSITION_CENTER);
        pressButtonReport.setTextVerticalPosition(PressButton.POSITION_CENTER);
        pressButtonReport.drawTextUnderline(true);

        pressButtonClear.setTextHorizontalPosition(PressButton.POSITION_CENTER);
        pressButtonClear.setTextVerticalPosition(PressButton.POSITION_CENTER);
        pressButtonClear.drawTextUnderline(true);

        ArrayList<Component> uiComponentOrder = new ArrayList<>();
        uiComponentOrder.add(inputDateFrom);
        uiComponentOrder.add(inputDateTo);
        uiComponentOrder.add(contactPicker1.getNumberField());
        uiComponentOrder.add(contactPicker1.getSearchField());
        uiComponentOrder.add(itemPicker1.getNumberField());
        uiComponentOrder.add(itemPicker1.getSearchField());
        uiComponentOrder.add(pressButtonReport);
        groupPane1.setFocusCycleRoot(true);
        groupPane1.setFocusTraversalPolicy(new CustomFocusTraversalPolicy(uiComponentOrder));

        reportTable.setReport((reportCustomerItemBill = new ReportCustomerItemBill()));

        int index = 0;
        reportTable.setColumnPreferredWidth(index++, 50);
        reportTable.setColumnPreferredWidth(index++, 70);
        reportTable.setColumnPreferredWidth(index++, 80);
        reportTable.setColumnPreferredWidth(index++, 80);
        reportTable.setColumnPreferredWidth(index++, 150);
        reportTable.setColumnPreferredWidth(index++, 80);
        reportTable.setColumnPreferredWidth(index++, 80);
        reportTable.setColumnPreferredWidth(index++, 220);
        reportTable.setColumnPreferredWidth(index++, 100);
        reportTable.setColumnPreferredWidth(index++, 100);
        reportTable.setColumnPreferredWidth(index++, 100);

        java.awt.EventQueue.invokeLater(() -> {
            contactPicker1.getNumberField().requestFocusInWindow();
        });

        JTable jTable = reportTable.getjTable();
        TableModelReport model = reportTable.getReportTableModel();
        TableRowSorter sorter = new TableRowSorter(model);
        jTable.setRowSorter(sorter);

        reportTable.setReverse(true);
        
        apply();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPane1 = new ui.container.GroupPane();
        inputDateTo = new ui.controls.input.InputFieldDate();
        inputDateFrom = new ui.controls.input.InputFieldDate();
        jSeparator1 = new javax.swing.JSeparator();
        pressButtonClear = new ui.controls.PressButton();
        pressButtonReport = new ui.controls.PressButton();
        jSeparator2 = new javax.swing.JSeparator();
        itemPicker1 = new application.ui.ItemPicker();
        contactPicker1 = new application.ui.ContactPicker();
        reportTable = new report.ui.ReportTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout(5, 5));

        groupPane1.setPreferredSize(new java.awt.Dimension(100, 60));

        inputDateTo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "تا تاریخ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        inputDateFrom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "از تاریخ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputDateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDateFromActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        pressButtonClear.setText("پاک کردن");
        pressButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressButtonClearMousePressed(evt);
            }
        });
        pressButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButtonClearActionPerformed(evt);
            }
        });

        pressButtonReport.setText("گزارش");
        pressButtonReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressButtonReportMousePressed(evt);
            }
        });
        pressButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButtonReportActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout groupPane1Layout = new javax.swing.GroupLayout(groupPane1);
        groupPane1.setLayout(groupPane1Layout);
        groupPane1Layout.setHorizontalGroup(
            groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPane1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(itemPicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactPicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pressButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pressButtonReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        groupPane1Layout.setVerticalGroup(
            groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemPicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(groupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pressButtonReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(pressButtonClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(groupPane1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(contactPicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );

        add(groupPane1, java.awt.BorderLayout.NORTH);
        add(reportTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pressButtonReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressButtonReportMousePressed
        apply();
    }//GEN-LAST:event_pressButtonReportMousePressed

    private void pressButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButtonReportActionPerformed
        apply();
    }//GEN-LAST:event_pressButtonReportActionPerformed

    private void pressButtonClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressButtonClearMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pressButtonClearMousePressed

    private void pressButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButtonClearActionPerformed
        clearInputs();
    }//GEN-LAST:event_pressButtonClearActionPerformed

    private void inputDateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDateFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDateFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private application.ui.ContactPicker contactPicker1;
    private ui.container.GroupPane groupPane1;
    private ui.controls.input.InputFieldDate inputDateFrom;
    private ui.controls.input.InputFieldDate inputDateTo;
    private application.ui.ItemPicker itemPicker1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private ui.controls.PressButton pressButtonClear;
    private ui.controls.PressButton pressButtonReport;
    private report.ui.ReportTable reportTable;
    // End of variables declaration//GEN-END:variables

    private void apply() {

        long dateStart = inputDateFrom.isValidInput() ? Long.parseLong(inputDateFrom.getText().replace("/", "")) : 0L;
        long dateEnd = inputDateTo.isValidInput() ? Long.parseLong(inputDateTo.getText().replace("/", "")) : Long.MAX_VALUE;

        long contactId = contactPicker1.getSelectedContact() == null
                ? 0L : contactPicker1.getSelectedContact().getContactId();

        long itemId = itemPicker1.getSelectedItem() == null
                ? 0L : itemPicker1.getSelectedItem().getItemId();

        reportTable.apply();

        ((TableRowSorter) reportTable.getjTable().getRowSorter()).setRowFilter(
                new RowFilter<TableModelReport, Object>() {
            @Override
            public boolean include(RowFilter.Entry<? extends TableModelReport, ? extends Object> entry) {
                boolean include = true;

                long date = Long.parseLong(entry.getValue(2).toString().replaceAll("/", ""));
                include &= (date >= dateStart && date <= dateEnd);

                if (contactId != 0) {
                    include &= (contactId == Long.parseLong(entry.getValue(3).toString()));
                }
                if (itemId != 0) {
                    include &= (itemId == Long.parseLong(entry.getValue(6).toString()));
                }

                return include;
            }
        });

    }

    private void clearInputs() {
        inputDateFrom.setText("");
        inputDateTo.setText("");

        contactPicker1.setSelectedContact(null);
        itemPicker1.setSelectedItem(null);

    }

    public void refreshTitle(TabbedContainer parent) {
        this.tabbedPane = parent;

        String title = "صورتحساب ";

        if (contactPicker1.getSelectedContact() != null) {
            title += "/" + contactPicker1.getSelectedContact().concatinatedInfo();
        } else {
            title += " مشتری";
        }
        if (itemPicker1.getSelectedItem() != null) {
            title += "/" + itemPicker1.getSelectedItem().getDescription();
        } else {
            title += "/کالا";
        }

        this.tabbedPane.setTitleAt(this.tabbedPane.indexOfComponent(this), title.trim());
    }
}
