/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report.ui;

import application.ui.ContactPicker;
import entity.Contact;
import invoice.ui.CustomFocusTraversalPolicy;
import java.awt.Component;
import java.util.ArrayList;
import report.ReportPaymentSum;
import ui.container.TabbedContainer;

/**
 *
 * @author PersianDevStudio
 */
public class ReportPanelPaymentSum extends javax.swing.JPanel {

    private final ReportPaymentSum report;
    private TabbedContainer tabbedContainer;

    private Contact contact;

    /**
     * Creates new form ReportPanelPaymentSum
     */
    public ReportPanelPaymentSum() {
        initComponents();

        reportTable.setReport((report = new ReportPaymentSum()));
        reportTable.apply();
        contactPicker1.setOnPick((Contact contact) -> {
            report.setContactId(contact == null ? 0 : contact.getContactId());
            ReportPanelPaymentSum.this.contact = contact;
            reportTable.apply();
            refreshTitle(tabbedContainer);
        });

        int pIndex = 0;
        reportTable.setColumnPreferredWidth(pIndex++, 50);
        reportTable.setColumnPreferredWidth(pIndex++, 230);
        reportTable.setColumnPreferredWidth(pIndex++, 120);
        reportTable.setColumnPreferredWidth(pIndex++, 120);
        reportTable.setColumnPreferredWidth(pIndex++, 120);
        reportTable.setColumnPreferredWidth(pIndex++, 120);

        ArrayList<Component> uiComponentOrder = new ArrayList<>();
        uiComponentOrder.add(contactPicker1.getNumberField());
        uiComponentOrder.add(contactPicker1.getSearchField());
        uiComponentOrder.add(pressButtonClear);
        groupPane2.setFocusCycleRoot(true);
        groupPane2.setFocusTraversalPolicy(new CustomFocusTraversalPolicy(uiComponentOrder));
        
        java.awt.EventQueue.invokeLater(() -> {
            contactPicker1.getNumberField().requestFocusInWindow();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPane1 = new ui.container.GroupPane();
        reportTable = new report.ui.ReportTable();
        groupPane2 = new ui.container.GroupPane();
        pressButtonClear = new ui.controls.PressButton();
        contactPicker1 = new application.ui.ContactPicker();

        setLayout(new java.awt.BorderLayout());

        groupPane1.setLayout(new java.awt.BorderLayout());
        groupPane1.add(reportTable, java.awt.BorderLayout.CENTER);

        add(groupPane1, java.awt.BorderLayout.CENTER);

        groupPane2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        pressButtonClear.setText("پاک کردن");
        pressButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButtonClearActionPerformed(evt);
            }
        });
        groupPane2.add(pressButtonClear);
        groupPane2.add(contactPicker1);

        add(groupPane2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void pressButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButtonClearActionPerformed
        clear();
    }//GEN-LAST:event_pressButtonClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private application.ui.ContactPicker contactPicker1;
    private ui.container.GroupPane groupPane1;
    private ui.container.GroupPane groupPane2;
    private ui.controls.PressButton pressButtonClear;
    private report.ui.ReportTable reportTable;
    // End of variables declaration//GEN-END:variables

    public void refreshTitle(TabbedContainer tabbedContainer) {
        this.tabbedContainer = tabbedContainer;

        String title = "گزارش بد/بس";

        if (contact != null) {
            title = " - " + contact.concatinatedInfo();
        }

        this.tabbedContainer.setTitleAt(this.tabbedContainer.indexOfComponent(this), title);
    }

    private void clear() {
        contact = null;
        contactPicker1.setSelectedContact(null);
        report.setContactId(0);
        reportTable.apply();
        refreshTitle(tabbedContainer);
    }
}
