/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.ui;

import entity.CashBox;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author PersianDevStudio
 */
public class CashBoxDialog extends javax.swing.JDialog {

    /**
     * Creates new form CashBoxDialog
     *
     * @param parent
     * @param modal
     */
    public CashBoxDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        loadCashboxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageButton1 = new ui.controls.ImageButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupPane1 = new ui.container.GroupPane();
        cashboxList = new ui.container.GroupPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imageButton1.setText("افرودن صدوق جدید");
        imageButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        groupPane1.setLayout(new java.awt.BorderLayout());

        cashboxList.setLayout(new java.awt.GridLayout(0, 1));
        groupPane1.add(cashboxList, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(groupPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(imageButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButton1ActionPerformed
        addNewCashBox();
    }//GEN-LAST:event_imageButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void open() {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CashBoxDialog dialog = new CashBoxDialog(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.container.GroupPane cashboxList;
    private ui.container.GroupPane groupPane1;
    private ui.controls.ImageButton imageButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void loadCashboxes() {
        
        cashboxList.removeAll();
        ArrayList<CashBox> all = CashBox.listAll();
        for (CashBox cashBox : all) {
            CashBoxListUI ui = new CashBoxListUI();
            ui.setDialog(CashBoxDialog.this);
            ui.setup(cashBox);
            cashboxList.add(ui);
        }
        
        cashboxList.revalidate();
        cashboxList.repaint();
        
    }
    
    private void addNewCashBox() {
        try {
            String title = JOptionPane.showInputDialog("عنوان صندوق");
            if (title == null) {
                return;
            }
            if (title.trim().isEmpty()) {
                NotificationManager.showError(cashboxList, "ورودی معتبر وارد کنید");
            } else {
                CashBox c = new CashBox();
                c.setTitle(title);
                c.insert();
                loadCashboxes();
            }
        } catch (SQLException ex) {
            NotificationManager.showError(cashboxList, ex.toString());
        }
    }
}
