/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.ui;

import application.Application;
import entity.CashBox;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import ui.AppTheme;
import ui.controls.PressButton;

/**
 *
 * @author PersianDevStudio
 */
public class CashBoxListUI extends javax.swing.JPanel {

    private CashBox cashbox;

    private CashBoxDialog dialog;

    public void setDialog(CashBoxDialog dialog) {
        this.dialog = dialog;
    }

    /**
     * Creates new form CashBoxListUI
     */
    public CashBoxListUI() {
        initComponents();

        textView1.setForeground(AppTheme.COLOR_MAIN);

        pressButton3.setTextHorizontalPosition(PressButton.POSITION_CENTER);
        pressButton1.setTextHorizontalPosition(PressButton.POSITION_CENTER);

        pressButton3.addActionListener((ActionEvent e) -> {
            try {
                String title = JOptionPane.showInputDialog("عنوان صندوق", cashbox.getTitle());
                if (title == null) {
                    return;
                }

                if (title.trim().isEmpty()) {
                    NotificationManager.showError(CashBoxListUI.this, "ورودی معتبر وارد کنید");
                } else {
                    cashbox.setTitle(title);
                    cashbox.update();
                    refresh();
                }
            } catch (SQLException ex) {
                NotificationManager.showError(CashBoxListUI.this, ex.toString());
            }
        });
    }

    public void setup(CashBox cashBox) {
        this.cashbox = cashBox;
        refresh();
    }

    private void refresh() {
        try {
            textView1.setText(this.cashbox.getTitle());
            textView2.setText("موجودی : " + cashbox.getBalance().stripTrailingZeros().toPlainString());
        } catch (SQLException ex) {
            NotificationManager.showError(this, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPane1 = new ui.container.GroupPane();
        pressButton3 = new ui.controls.PressButton();
        pressButton1 = new ui.controls.PressButton();
        groupPane2 = new ui.container.GroupPane();
        textView1 = new ui.controls.TextView();
        textView2 = new ui.controls.TextView();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5))));

        pressButton3.setText("ویرایش");
        pressButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButton3ActionPerformed(evt);
            }
        });
        groupPane1.add(pressButton3);

        pressButton1.setText("واریز وجه");
        pressButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButton1ActionPerformed(evt);
            }
        });
        groupPane1.add(pressButton1);

        groupPane2.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        textView1.setForeground(new java.awt.Color(102, 102, 102));
        textView1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textView1.setText("عنوان صندوق");
        textView1.setFont(new java.awt.Font("B yekan+", 1, 13)); // NOI18N
        groupPane2.add(textView1);

        textView2.setForeground(new java.awt.Color(51, 51, 51));
        textView2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textView2.setText("موجودی : 1300000");
        groupPane2.add(textView2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(groupPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(groupPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(groupPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(groupPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pressButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pressButton3ActionPerformed

    private void pressButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButton1ActionPerformed
        chargeCashBox();
    }//GEN-LAST:event_pressButton1ActionPerformed

    private void chargeCashBox() {
        JDialog d = new JDialog(dialog, true);
        d.setTitle("افزایش موجودی");
        PaymentDocument paymentDocument = new PaymentDocument();
        paymentDocument.getPressButtonDelete().setVisible(false);
        paymentDocument.getPressButtonSave().addActionListener((ActionEvent e) -> {
            paymentDocument.insertInfo();
            d.dispose();
            dialog.loadCashboxes();
        });

        paymentDocument.setCashBox(cashbox);
        d.getContentPane().setLayout(new CardLayout());
        d.getContentPane().add(paymentDocument);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.container.GroupPane groupPane1;
    private ui.container.GroupPane groupPane2;
    private ui.controls.PressButton pressButton1;
    private ui.controls.PressButton pressButton3;
    private ui.controls.TextView textView1;
    private ui.controls.TextView textView2;
    // End of variables declaration//GEN-END:variables

}
