/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.ui;

import entity.Contact;
import entity.invoice.Invoice;
import java.awt.event.KeyEvent;
import javax.swing.border.TitledBorder;
import ui.controls.input.InputField;
import ui.controls.input.InputFieldNumber;
import ui.controls.input.SearchBox;
import ui.controls.input.SearchBoxEditor;

/**
 *
 * @author PersianDevStudio
 */
public class ContactPicker extends javax.swing.JPanel {

    private Contact selectedContact;

    private OnPickContact onPick;

    /**
     * Creates new form ContactPicker
     */
    public ContactPicker() {
        initComponents();

        SearchBox.setupSearchbox(Contact.class,
                searchBox,
                "CALL search_contact(?)",
                (Object currentValue) -> {
                    setSelectedContact((Contact) currentValue);
                });
    }

    public void setSelectedContact(Contact contact) {
        this.selectedContact = contact;

        if (searchBox.getSelectedItem() != selectedContact) {
            searchBox.setSelectedItem(selectedContact);
        }
        inputFieldNumber.setText(selectedContact == null ? "" : selectedContact.getContactId() + "");

        if (onPick != null) {
            onPick.onPick(selectedContact);
        }
    }

    public Contact getSelectedContact() {
        return selectedContact;
    }

    public InputFieldNumber getNumberField() {
        return inputFieldNumber;
    }

    public InputField getSearchField() {
        return ((SearchBoxEditor) searchBox.getEditor()).getInputField();
    }

    private void findContactWithId() {
        if (false == inputFieldNumber.getText().trim().isEmpty()) {
            Contact contact = Contact.find(Long.parseLong(inputFieldNumber.getText()));
            if (contact == null) {
                NotificationManager.showMessage(this, "شناسه وارد شده موجود نیست!");
                inputFieldNumber.requestFocusInWindow();
            } else {
                setSelectedContact(contact);
            }
        }
    }

    public void setOnPick(OnPickContact onPick) {
        this.onPick = onPick;
    }

    public void updateTitles(int operationType) {
        String contactTitle;
        if (Invoice.inoutBuy(operationType)) {
            contactTitle = "فروشنده";
        } else {
            contactTitle = "خریدار";
        }
        ((TitledBorder) searchBox.getBorder()).setTitle(contactTitle);
        ((TitledBorder) inputFieldNumber.getBorder()).setTitle("کد " + contactTitle);
    }

    public interface OnPickContact {

        public void onPick(Contact contact);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFieldNumber = new ui.controls.input.InputFieldNumber();
        searchBox = new ui.controls.input.SearchBox();

        setLayout(new java.awt.BorderLayout());

        inputFieldNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "شناسه", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputFieldNumber.setPreferredSize(new java.awt.Dimension(120, 39));
        inputFieldNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputFieldNumberFocusLost(evt);
            }
        });
        inputFieldNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputFieldNumberKeyPressed(evt);
            }
        });
        add(inputFieldNumber, java.awt.BorderLayout.EAST);

        searchBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "فروشنده/خریدار", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        add(searchBox, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFieldNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            findContactWithId();
        }
    }//GEN-LAST:event_inputFieldNumberKeyPressed

    private void inputFieldNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFieldNumberFocusLost
         findContactWithId();
    }//GEN-LAST:event_inputFieldNumberFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.controls.input.InputFieldNumber inputFieldNumber;
    private ui.controls.input.SearchBox searchBox;
    // End of variables declaration//GEN-END:variables

}
