/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.ui;

import application.NotificationManager;
import entity.Item;
import java.awt.event.KeyEvent;
import ui.container.GroupPane;
import ui.controls.input.InputField;
import ui.controls.input.InputFieldNumber;
import ui.controls.input.SearchBox;
import ui.controls.input.SearchBoxEditor;

/**
 *
 * @author PersianDevStudio
 */
public class ItemPicker extends GroupPane {

    private Item selectedItem;

    private OnPickItem onPick;

    /**
     * Creates new form ItemPickPanel
     */
    public ItemPicker() {
        initComponents();

        SearchBox.setupSearchbox(Item.class,
                searchBox,
                "CALL search_item(?)",
                (Object currentValue) -> {
                    setSelectedItem((Item) currentValue);
                });
    }

    public void setSelectedItem(Item selectedItem) {
        this.selectedItem = selectedItem;

        if (searchBox.getSelectedItem() != selectedItem) {
            searchBox.setSelectedItem(selectedItem);
        }
        inputFieldNumber.setText(selectedItem == null ? "" : selectedItem.getItemId() + "");

        if (onPick != null) {
            onPick.onPick(selectedItem);
        }

    }

    public Item getSelectedItem() {
        return selectedItem;
    }

    private void findItemWithId() {
        if (false == inputFieldNumber.getText().trim().isEmpty()) {
            Item item = Item.find(Long.parseLong(inputFieldNumber.getText()));
            if (item == null) {
                NotificationManager.showMessage(this, "شناسه وارد شده موجود نیست!");
                inputFieldNumber.requestFocusInWindow();
            } else {
                setSelectedItem(item);
            }
        }
    }

    public void setOnPick(OnPickItem onPick) {
        this.onPick = onPick;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBox = new ui.controls.input.SearchBox();
        inputFieldNumber = new ui.controls.input.InputFieldNumber();

        setLayout(new java.awt.BorderLayout());

        searchBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "عنوان کالا", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        add(searchBox, java.awt.BorderLayout.CENTER);

        inputFieldNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "شناسه کالا", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputFieldNumber.setPreferredSize(new java.awt.Dimension(130, 39));
        inputFieldNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputFieldNumberFocusLost(evt);
            }
        });
        inputFieldNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputFieldNumberKeyPressed(evt);
            }
        });
        add(inputFieldNumber, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFieldNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            findItemWithId();
        }
    }//GEN-LAST:event_inputFieldNumberKeyPressed

    private void inputFieldNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFieldNumberFocusLost
       findItemWithId();
    }//GEN-LAST:event_inputFieldNumberFocusLost

    public InputFieldNumber getNumberField() {
        return inputFieldNumber;
    }

    public InputField getSearchField() {
        return ((SearchBoxEditor) searchBox.getEditor()).getInputField();
    }

    public interface OnPickItem {

        public void onPick(Item item);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.controls.input.InputFieldNumber inputFieldNumber;
    private ui.controls.input.SearchBox searchBox;
    // End of variables declaration//GEN-END:variables

}
