/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.ui;

import entity.CashBox;
import entity.Payment;
import entity.invoice.Invoice;
import entity.invoice.InvoiceManager;
import invoice.ui.CustomFocusTraversalPolicy;
import java.awt.Component;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import ui.controls.PressButton;

/**
 *
 * @author PersianDevStudio
 */
public class PaymentDocument extends javax.swing.JPanel {

    private CashBox cashBox;

    /**
     * Creates new form PaymentDocument
     */
    public PaymentDocument() {
        initComponents();

        pressButtonDelete.setTextHorizontalPosition(PressButton.POSITION_CENTER);
        pressButtonSave.setTextHorizontalPosition(PressButton.POSITION_CENTER);

        ArrayList<Component> uiComponentOrder = new ArrayList<>();
        uiComponentOrder.add(pressButtonDelete);
        uiComponentOrder.add(inputFieldNumber1);
        uiComponentOrder.add(inputFieldDate1);
        uiComponentOrder.add(contactPicker1.getNumberField());
        uiComponentOrder.add(contactPicker1.getSearchField());
        uiComponentOrder.add(comboList1);
        uiComponentOrder.add(pressButtonSave);
        groupPane1.setFocusCycleRoot(true);
        groupPane1.setFocusTraversalPolicy(new CustomFocusTraversalPolicy(uiComponentOrder));

        java.awt.EventQueue.invokeLater(() -> {
            inputFieldNumber1.requestFocusInWindow();
        });
    }

    public void setCashBox(CashBox cashBox) {
        this.cashBox = cashBox;
        refresh();
    }

    public void insertInfo() {

        try {
            Invoice i = new Invoice();
            i.setContact(contactPicker1.getSelectedContact().getContactId());
            i.setDate(Long.parseLong(inputFieldDate1.getText().replace("/", "")));
            i.setStorePayment(null);
            i.setOperationType(Invoice.TYPE_OTHER);

            Payment p = new Payment();
            //it means the contact is creditor of cashbox
            //cashbox is the deptor
            p.setCreditor(new BigDecimal(inputFieldNumber1.getText()));

            p.setContact(contactPicker1.getSelectedContact().getContactId());
            p.setObjectId(((CashBox) comboList1.getSelectedItem()).cashboxId);
            p.setObjectType(Payment.CASH_BOX);
            i.addPayment(p);

            InvoiceManager.insert(i);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentDocument.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public PressButton getPressButtonDelete() {
        return pressButtonDelete;
    }

    public void setPressButtonDelete(PressButton pressButtonDelete) {
        this.pressButtonDelete = pressButtonDelete;
    }

    public PressButton getPressButtonSave() {
        return pressButtonSave;
    }

    public void setPressButtonSave(PressButton pressButtonSave) {
        this.pressButtonSave = pressButtonSave;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        groupPane1 = new ui.container.GroupPane();
        pressButtonSave = new ui.controls.PressButton();
        comboList1 = new ui.controls.ComboList();
        contactPicker1 = new application.ui.ContactPicker();
        inputFieldDate1 = new ui.controls.input.InputFieldDate();
        inputFieldNumber1 = new ui.controls.input.InputFieldNumber();
        pressButtonDelete = new ui.controls.PressButton();

        setLayout(new java.awt.BorderLayout());
        add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        pressButtonSave.setText("ثبت");
        pressButtonSave.setPreferredSize(new java.awt.Dimension(97, 35));
        groupPane1.add(pressButtonSave);

        comboList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "صندوق / بانک", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        comboList1.setPreferredSize(new java.awt.Dimension(120, 40));
        groupPane1.add(comboList1);
        groupPane1.add(contactPicker1);

        inputFieldDate1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "تاریخ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        groupPane1.add(inputFieldDate1);

        inputFieldNumber1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "مبلغ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputFieldNumber1.setPreferredSize(new java.awt.Dimension(130, 39));
        groupPane1.add(inputFieldNumber1);

        pressButtonDelete.setText("حذف");
        pressButtonDelete.setPreferredSize(new java.awt.Dimension(97, 35));
        groupPane1.add(pressButtonDelete);

        add(groupPane1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.controls.ComboList comboList1;
    private application.ui.ContactPicker contactPicker1;
    private ui.container.GroupPane groupPane1;
    private ui.controls.input.InputFieldDate inputFieldDate1;
    private ui.controls.input.InputFieldNumber inputFieldNumber1;
    private javax.swing.JSeparator jSeparator1;
    private ui.controls.PressButton pressButtonDelete;
    private ui.controls.PressButton pressButtonSave;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        if (cashBox != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    comboList1.setModel(new DefaultComboBoxModel(CashBox.listAll().toArray()));
                    comboList1.setSelectedItem(cashBox);
                }
            });

        }
    }

}
