/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.ui;

import application.Application;
import application.printer.Settings;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ui.controls.PressButton;

/**
 *
 * @author PersianDevStudio
 */
public class PrinterSettingsDialog extends javax.swing.JDialog {

    /**
     * Creates new form PrinterSettingsDialog
     *
     * @param parent
     * @param modal
     */
    public PrinterSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        pressButtonApply.setTextHorizontalPosition(PressButton.POSITION_CENTER);
        pressButtonApply.setTextVerticalPosition(PressButton.POSITION_CENTER);

        inputHorizontalPadding.setText(Settings.getInt(Settings.KEY_PRINT_HORIZONTAL_PADDING) + "");
        inputVerticalPadding.setText(Settings.getInt(Settings.KEY_PRINT_VERTICAL_PADDING) + "");
        inputPageWidth.setText(Settings.getInt(Settings.KEY_PRINT_PAPER_WIDTH) + "");
        inputPageHeight.setText(Settings.getInt(Settings.KEY_PRINT_PAPER_HEIGHT) + "");
        inputFieldShopTitle.setText(Settings.getString(Settings.KEY_SHOP_TITLE));

    }

    private void save() {
        try {
            if (inputHorizontalPadding.getText().trim().isEmpty()
                    || inputVerticalPadding.getText().trim().isEmpty()
                    || inputPageWidth.getText().trim().isEmpty()
                    || inputFieldShopTitle.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "هیچ کدام از فیلد ها نباید خالی باشد", "خطا", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Settings.save(Settings.KEY_PRINT_HORIZONTAL_PADDING, inputHorizontalPadding.getText().trim());
            Settings.save(Settings.KEY_PRINT_VERTICAL_PADDING, inputVerticalPadding.getText().trim());
            Settings.save(Settings.KEY_PRINT_PAPER_WIDTH, inputPageWidth.getText().trim());
            Settings.save(Settings.KEY_PRINT_PAPER_HEIGHT, inputPageHeight.getText().trim());
            Settings.save(Settings.KEY_SHOP_TITLE, inputFieldShopTitle.getText().trim());
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString(), "خطا", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputHorizontalPadding = new ui.controls.input.InputFieldNumber();
        inputVerticalPadding = new ui.controls.input.InputFieldNumber();
        inputPageWidth = new ui.controls.input.InputFieldNumber();
        inputPageHeight = new ui.controls.input.InputFieldNumber();
        inputFieldShopTitle = new ui.controls.input.InputField();
        pressButtonApply = new ui.controls.PressButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        inputHorizontalPadding.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "حاشیه افقی", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputHorizontalPadding.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputHorizontalPadding.setOpaque(false);
        inputHorizontalPadding.setPreferredSize(new java.awt.Dimension(300, 39));
        getContentPane().add(inputHorizontalPadding);

        inputVerticalPadding.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "حاشیه عمودی", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputVerticalPadding.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputVerticalPadding.setOpaque(false);
        inputVerticalPadding.setPreferredSize(new java.awt.Dimension(200, 39));
        getContentPane().add(inputVerticalPadding);

        inputPageWidth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "پهنای صفحه", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputPageWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputPageWidth.setOpaque(false);
        inputPageWidth.setPreferredSize(new java.awt.Dimension(200, 39));
        getContentPane().add(inputPageWidth);

        inputPageHeight.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ارتفاع صفحه", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputPageHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputPageHeight.setOpaque(false);
        inputPageHeight.setPreferredSize(new java.awt.Dimension(200, 39));
        getContentPane().add(inputPageHeight);

        inputFieldShopTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "عنوان فروشگاه", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        inputFieldShopTitle.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputFieldShopTitle.setOpaque(false);
        inputFieldShopTitle.setPreferredSize(new java.awt.Dimension(200, 39));
        getContentPane().add(inputFieldShopTitle);

        pressButtonApply.setText("اعمال تغییرات");
        pressButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressButtonApplyActionPerformed(evt);
            }
        });
        getContentPane().add(pressButtonApply);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pressButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressButtonApplyActionPerformed
        save();
    }//GEN-LAST:event_pressButtonApplyActionPerformed

    public static void open() {
        PrinterSettingsDialog dialog = new PrinterSettingsDialog(Application.instance, true);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.controls.input.InputField inputFieldShopTitle;
    private ui.controls.input.InputFieldNumber inputHorizontalPadding;
    private ui.controls.input.InputFieldNumber inputPageHeight;
    private ui.controls.input.InputFieldNumber inputPageWidth;
    private ui.controls.input.InputFieldNumber inputVerticalPadding;
    private ui.controls.PressButton pressButtonApply;
    // End of variables declaration//GEN-END:variables

}
